### ISSUE TITLE
生成证书出错

### ISSUE THREAD

**Issue by fnoopv** [bigfile/bigfile#33]
**Describe the bug**

- go version: no
- bigfile version (or commit ref): no
- operating system: no
- mysql version no
- docker image version: v1.0.2

## Description
运行`docker run -v $(pwd):/certs bigfile/bigfile rpc:make-cert --save-to /certs`命令时没有生成证书
## Screenshots
![image](https://user-images.githubusercontent.com/24599198/64964542-d5e59900-d8cd-11e9-9cad-c5c50cf6ab26.png)

**Comment by gamelife1314** [comment]
试一下最新的镜像，刚才打包的最新版本

> docker run -v $(pwd):/certs bigfile/bigfile:v1.0.4 rpc:make-cert --save-to /certs

![image](https://user-images.githubusercontent.com/10297148/64966603-adf83480-d8d1-11e9-8674-8f1e6f4915a5.png)

**Comment by gamelife1314** [comment]
试了下 **v1.0.2**，我这里也是没问题，拉一下最新镜像

![image](https://user-images.githubusercontent.com/10297148/64967340-e5b3ac00-d8d2-11e9-8bb3-fdf13d774610.png)

**Comment by fnoopv** [comment]
> 试了下 **v1.0.2**，我这里也是没问题，拉一下最新镜像
> 
> ![image](https://user-images.githubusercontent.com/10297148/64967340-e5b3ac00-d8d2-11e9-8bb3-fdf13d774610.png)

还是报一样的错，难道是因为我用的是arm？我找个x86试试

**Comment by gamelife1314** [comment]
是的，Docker 里面的镜像是 linux Amd64，我再制作个新版镜像

**Comment by fnoopv** [comment]
> 是的，Docker 里面的镜像是 linux Amd64，我再制作个新版镜像

麻烦了

**Comment by gamelife1314** [comment]
@fnoopv 测试一下这个镜像：

> docker run -v $(pwd):/certs bigfile/bigfile:latest-arm64 rpc:make-cert --save-to /certs

**Comment by gamelife1314** [comment]
@fnoopv 没事，感谢你提出问题，我这边没有合适的机器测试。试试这个：

```
docker run -v $(pwd):/certs bigfile/bigfile:latest-arm64 rpc:make-cert --save-to /certs
```

**Comment by gamelife1314** [comment]
是的，这个是 armv8，我做天刚把 arm6和7的去掉，我在加进去吧
